// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7cAf_7mThgP0aG1gLtRr-rnykX72bwu0',
    appId: '1:535176782346:web:2d0401237d0849bc87f5f3',
    messagingSenderId: '535176782346',
    projectId: 'let-s-chat-ca2df',
    authDomain: 'let-s-chat-ca2df.firebaseapp.com',
    storageBucket: 'let-s-chat-ca2df.appspot.com',
    measurementId: 'G-F13L0PJ03X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSTdsWpTuaLce5CPdwMAK2yMQdxXLovyk',
    appId: '1:535176782346:android:0a2c540e56c23fcc87f5f3',
    messagingSenderId: '535176782346',
    projectId: 'let-s-chat-ca2df',
    storageBucket: 'let-s-chat-ca2df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwCMtKST8bU4yJrS_4Pkj5-C4i-N06nKk',
    appId: '1:535176782346:ios:166487bd6f7ade3887f5f3',
    messagingSenderId: '535176782346',
    projectId: 'let-s-chat-ca2df',
    storageBucket: 'let-s-chat-ca2df.appspot.com',
    androidClientId: '535176782346-8schjqco2br6ebap8evffspmtkgctlkf.apps.googleusercontent.com',
    iosClientId: '535176782346-6i0c2o25mgtjhdc3mbfc5l282j7tlnp1.apps.googleusercontent.com',
    iosBundleId: 'com.akshar2324.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwCMtKST8bU4yJrS_4Pkj5-C4i-N06nKk',
    appId: '1:535176782346:ios:0d1108d1edddeef887f5f3',
    messagingSenderId: '535176782346',
    projectId: 'let-s-chat-ca2df',
    storageBucket: 'let-s-chat-ca2df.appspot.com',
    androidClientId: '535176782346-8schjqco2br6ebap8evffspmtkgctlkf.apps.googleusercontent.com',
    iosClientId: '535176782346-qi2005tbabhohtt7ikq5rl0riiuauvas.apps.googleusercontent.com',
    iosBundleId: 'com.akshar2324.chatApp.RunnerTests',
  );
}
